
package it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv;

import javax.xml.ws.WebFault;

/**
 * This class was generated by Apache CXF 3.1.6 2017-03-07T16:14:32.051+01:00
 * Generated source version: 3.1.6
 */

@SuppressWarnings("serial")
@WebFault(name = "SigopMaxRecordException", targetNamespace = "http://ws.business.sigop.csi.it/")
public class SigopMaxRecordException_Exception extends Exception
{
  private it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.SigopMaxRecordException sigopMaxRecordException;

  public SigopMaxRecordException_Exception()
  {
    super();
  }

  public SigopMaxRecordException_Exception(String message)
  {
    super(message);
  }

  public SigopMaxRecordException_Exception(String message, Throwable cause)
  {
    super(message, cause);
  }

  public SigopMaxRecordException_Exception(String message,
      it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.SigopMaxRecordException sigopMaxRecordException)
  {
    super(message);
    this.sigopMaxRecordException = sigopMaxRecordException;
  }

  public SigopMaxRecordException_Exception(String message,
      it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.SigopMaxRecordException sigopMaxRecordException,
      Throwable cause)
  {
    super(message, cause);
    this.sigopMaxRecordException = sigopMaxRecordException;
  }

  public it.csi.iuffi.iuffiweb.integration.ws.sigop.sigopserv.SigopMaxRecordException getFaultInfo()
  {
    return this.sigopMaxRecordException;
  }
}
